name: "package build and deploy"
on: [push]

jobs:

  publish_python_package:
    name: publish python package
    runs-on: ubuntu-latest
    env:
        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install pip
        run: pip install pip==21.2.4 setuptools==57.4.0 wheel
      - name: create packages
        run: cd pyasciinet && bash build.sh
      - name: upload source package
        if: ${{ ( github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
        run: curl -F package=@$(ls pyasciinet/dist/asciinet-*.tar.gz) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
      - name: upload wheel
        if: ${{ (github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
        run: curl -F package=@$(ls pyasciinet/dist/asciinet-*.whl) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
      - name: publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: pyasciinet/dist

#  conda_package_build:
#    name: conda package build (and upload if release)
#    runs-on: ubuntu-latest
#    steps:
#      - name: "Set up Python 3.9"
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.9"
#      - name: pip cache
#        id: pip-cache
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - name: install kiara
#        run: pip install -U --extra-index-url https://pypi.fury.io/dharpa/ .
#      - name: install required plugin packages
#        run: pip install -U --pre --extra-index-url https://pypi.fury.io/dharpa/ kiara_plugin.develop
#      - name: build conda package
#        if: ${{ ( github.ref == 'refs/heads/master') }}
#        run: kiara conda build-package --patch-data ci/conda/conda-pkg-patch.yaml .
#      - name: extract tag name
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#      - name: build & publish conda package
#        if: ${{ startsWith(github.ref, 'refs/tags/') }}
#        run: kiara conda build-package --publish --user dharpa --token ${{ secrets.ANACONDA_PUSH_TOKEN }} --patch-data ci/conda/conda-pkg-patch.yaml .

